version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
      nodejs: 16
    commands:
      - pip install -r requirements.txt
      - npm install -g aws-cdk

  pre_build:
    commands:
      - export PYTHONPATH=$PYTHONPATH:/path/to/your/aws_cdk/installation
      - python app_test.py
