version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - python -m venv env
      - source env/bin/activate || . env/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python app_test.py
  build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
