version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      # Navigate to the correct directory
      - cd /codebuild/output/src498875578/src/github.com/VinodPandhare/ecs-devops-sandbox/ecs_devops_sandbox_cdk || { echo "Directory not found"; exit 1; }

      # Install dependencies using pip directly
      - pip install flask jinja2  # Example dependencies

  pre_build:
    commands:
      - python app_test.py

  build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
