version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
      nodejs: 16
    commands:
      - pip install -r requirements.txt
      - npm install -g aws-cdk

  pre_build:
    commands:
      - export PYTHONPATH=$PYTHONPATH:/root/.npm-global/lib/node_modules/aws-cdk/lib  # Adjust this path as per your npm global installation
      - python app_test.py
