version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
      nodejs: 14  # Ensure Node.js is installed (adjust version as needed)
    commands:
      - pip install -r requirements.txt  # Install Python dependencies if any
      - npm install -g aws-cdk  # Install AWS CDK globally with npm

  pre_build:
    commands:
      - python app_test.py
