version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - python -m venv env
      - source env/bin/activate
      - pip install --upgrade pip
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python app_test.py
